server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: micoserice-ribbon
#management:
 # port: 54001
 # health:
  #  mail:
   #   enabled: false


